# Environment Settings
# These settings specify the hardware and distributed setup for the model training.
# Adjust `num_gpus` and `dist_config` according to your distributed training environment.
env_setting:
  num_gpus: 1  # Number of GPUs. Now we don't support CPU mode. 
  num_workers: 8  # Number of worker threads for data loading.
  seed: 1234  # Seed for random number generators to ensure reproducibility.
  stdout_interval: 10

# Datapath Configuratoin
data_cfg:
  test_clean_json: data/test_clean.json
  test_noisy_json: data/test_noisy.json

# Training Configuration
# This section details parameters that directly influence the training process,
# including batch sizes, learning rates, and optimizer specifics.
training_cfg:
  batch_size: 4  # Training batch size.
  segment_size: 32000  # Audio segment size used during training, dependent on sampling rate.
  use_PCS400: False  # Use PCS or not

# STFT Configuration
# Configuration for Short-Time Fourier Transform (STFT), crucial for audio processing models.
stft_cfg:
  sampling_rate: 16000  # Audio sampling rate in Hz.
  n_fft: 400  # FFT components for transforming audio signals.
  hop_size: 100  # Samples between successive frames.
  win_size: 400  # Window size used in FFT.

# Model Configuration
model_cfg:
  thf: True  # Model type
  compress_factor: 1

# Room Impulse Response Generator Configuration
# Configuration for Short-Time Fourier Transform (STFT), crucial for audio processing models.
rir_cfg:
  type: RIR # Type of simulation, "RIR" for Room Impulse Response. "PyRoom" for Pyroomacoustics simulation.
  sampling_rate: 16000  # Audio sampling rate in Hz.
  reverberation_times: [0.15, 0.175, 0.2, 0.225, 0.25]  # reverberation times to simulate.
  rir_samples: 512
  hp_filter: True  # high-pass filter.
  version: 3  # simulation version.
